$(document).ready(function() {

    /* Focus on Homepage Search */
    $('#search').focus();
    
    /* Search Auto-Complete
        - Strict left-to-right string comparisons
    */
    var itemNames = [
        "Annihilus",
        "Hellfire Torch",
        "Constricting Ring",
        "Arachnid Mesh",
        "Azurewrath",
        "Tyrael's Might",
        "Crown of Ages",
        "Mang Song's Lesson",
        "Stormlash",
        "Tomb Reaver",
        "Unearthed Wand",
        "Alma Negra",
        "Andariel's Visage",
        "Archon Staff",
        "Arioc's Needle",
        "Arkaine's Valor",
        "Berserker Axe",
        "Bloodlord Skull",
        "Caduceus",
        "Colossus Blade",
        "Colossus Girdle",
        "Corona",
        "Diadem",
        "Dimensional Shard",
        "Dream Spirit",
        "Giant Thresher",
        "Glorious Axe",
        "Guardian Crown",
        "Halaberd's Reign",
        "Hydra Bow",
        "Kira's Guardian",
        "Legend Spike",
        "Metalgrid",
        "Myrmidon Greaves",
        "Mythical Sword",
        "Ogre Gauntlets",
        "Sacred Armor",
        "Scissors Suwayyah",
        "Shadowkiller",
        "The Cranium Basher",
        "The Gladiator's Bane",
        "The Grandfather",
        "Thunder Maul",
        "Vortex Shield",
        "War Pike",
        "Winged Harpoon",
        "Wolfhowl",
        "Archon Plate",
        "Bone Visage",
        "Boneshade",
        "Demon Crossbow",
        "Dracul's Grasp",
        "Dragonscale",
        "Great PoleAxe",
        "Griffon's Eye",
        "Hellrack",
        "Medusa's Gaze",
        "Vortex Orb",
        "Ward",
        "Wisp Projector",
        "Wraithflight",
        "Executioner's Justice",
        "Fanged Knife",
        "Ghost Spear",
        "Headhunter's Glory",
        "Ormus' Robes",
        "Schaefer's Hammer",
        "Shadow Plate",
        "Shillelah",
        "Sky Spirit",
        "The Reaper's Toll",
        "Warshrike",
        "Champion Axe",
        "Cryptic Sword",
        "Ethereal Edge",
        "Lacquered Plate",
        "Legendary Mallet",
        "Ravenlore",
        "Souldrain",
        "Templar's Might",
        "Troll Belt",
        "Zakarum Shield",
        "Fathom",
        "Kraken Shell",
        "Matriarchal Pike",
        "Mirrored Boots",
        "Runic Talons",
        "Succubae Skull",
        "Boneflame",
        "Colossal Sword",
        "Conqueror Crown",
        "Eschuta's temper",
        "Mara's Kaleidoscope",
        "Runemaster",
        "The Reedeemer",
        "Ward Bow",
        "Windforce",
        "Winged Axe",
        "Aegis",
        "Bloodraven's Charge",
        "Cryptic Axe",
        "Flamebellow",
        "Ghost Glaive",
        "Gutsiphon",
        "Shadowdancer",
        "Spired Helm",
        "Viperfork",
        "War Spike",
        "Conquest Sword",
        "Deathcleaver",
        "Feral Claws",
        "Frostwind",
        "Gargoyle's Bite",
        "Gimmershred",
        "Grand Matron Bow",
        "Hellforge Plate",
        "Spike Thorn",
        "Steelrend",
        "Stormspire",
        "Champion Sword",
        "Crusader Bow",
        "Eaglehorn",
        "Earthshifter",
        "Nature's Peace",
        "Steelpillar",
        "Stormshield",
        "Thunderstroke",
        "Veil of Steel",
        "Winged Knife",
        "Balrog Skin",
        "Crusader Gauntlets",
        "Demon's Arch",
        "Earth Spirit",
        "Fleshripper",
        "Lacerator",
        "Nord's Tenderizer",
        "Scourge",
        "Seraph Rod",
        "Spirit Ward",
        "Stone Crusher",
        "Troll Nest",
        "Windhammer",
        "Colossus Crossbow",
        "Demon Heart",
        "Doombringer",
        "Firelizard's Talons",
        "Great Hauberk",
        "Lich Wand",
        "Messerschmidt's Reaver",
        "Mithril Coil",
        "Nightwing's Veil",
        "Razoredge",
        "Spiritkeeper",
        "Deaths's Web",
        "Demonhead",
        "Elder Staff",
        "Jadetalon",
        "Mancatcher",
        "Marrowwalk",
        "Ondal's Wisdom",
        "Steel Carapice",
        "Battle Cestus",
        "Decapitator",
        "Destroyer Helm",
        "Djinnslayer",
        "Giantskull",
        "Highlord's Wrath",
        "Leviathan",
        "Loricated Mail",
        "Phase Blade",
        "Seraph's Hymn",
        "The Rising Sun",
        "Widowmaker",
        "Bonehew",
        "Boneweave Boots",
        "Darkforge Spawn",
        "Diamond Bow",
        "Diamond Mail",
        "Horizon's Tornado",
        "Monarch",
        "Sandstorm Trek",
        "Stoneraven",
        "Balrog Blade",
        "Balrog Spear",
        "Cerebus",
        "Cranebeak",
        "Demonlimb",
        "Hellslayer",
        "Thresher",
        "Verdugo's Hearty Cord",
        "Baranar's Star",
        "Devil Star",
        "Ettin Axe",
        "Gheed's Fortune",
        "Ghostflame",
        "Mithral Point",
        "Sacred Rondache",
        "Steelshade",
        "Tiara",
        "Wire Fleece",
        "Bloodmoon",
        "Demonhorn's Edge",
        "Harlequin Crest",
        "Heaven's Light",
        "Hydra Edge",
        "Ogre Maul",
        "Sun Spirit",
        "Vambraces",
        "Wizardspike",
        "Armet",
        "Blade Barrier",
        "Carrion Wind",
        "Great Bow",
        "Ironward",
        "Nosferatu's Coil",
        "Scarab Husk",
        "Vampirefang Belt",
        "War Fist",
        "Blackoak Shield",
        "Eldritch Orb",
        "Gorgon Crossbow",
        "Hellspawn Skull",
        "Wyrmhide",
        "Bul Katho's Wedding Band",
        "Fury Visor",
        "Highland Blade",
        "Lightsabre",
        "Overseer Skull",
        "Scarabshell Boots",
        "Stalagmite",
        "Stygian Pike",
        "Dusk Shroud",
        "Ghost Wand",
        "Matriarchal Javelin",
        "Silver Edged Axe",
        "The Scalper",
        "Colossus Voulge",
        "Flying Knife",
        "Hyperion",
        "Ornate Plate",
        "Corpsemourn",
        "Elegant Blade",
        "Hydraskull",
        "Reinforced Mace",
        "Sacred Targe",
        "Shadow Bow",
        "Vampirebone Gloves",
        "Blood Spirit",
        "Boneweave",
        "Mighty Scepter",
        "Stygian Pilum",
        "Wrist Sword",
        "Ataghan",
        "Black Hades",
        "Chaos Armor",
        "Luna",
        "Matriarchal Spear",
        "Small Crescent",
        "Spiderweb Sash",
        "Atma's Scarab",
        "Blade Bow",
        "Carnage Helm",
        "Mage Plate",
        "Ogre Axe",
        "Wyrmhide Boots",
        "Atma's Wail",
        "Buriza-Do Kyanon",
        "Heavenly Stone",
        "Legend Sword",
        "Minion Skull",
        "Que-Hegan's Wisdon",
        "Suwayyah",
        "Bone Knife",
        "Crescent Moon",
        "Embossed Plate",
        "Heater",
        "Hyperion Spear",
        "Radimant's Sphere",
        "Shako",
        "The Cat's Eye",
        "Walking Stick",
        "Bramble Mitts",
        "Crown of Thieves",
        "Demon Machine",
        "Feral Axe",
        "Pellet Bow",
        "Tyrant Club",
        "Ancient Shield",
        "Bloodtree Stump",
        "Falcata",
        "Flying Axe",
        "Guardian Naga",
        "Toothrow",
        "Dangoon's Teaching",
        "Gorerider",
        "Grand Crown",
        "Grim Scythe",
        "Haemosu's Adament",
        "Heaven's Taebaek",
        "Hellmouth",
        "Ondal's Almighty",
        "Polished Wand",
        "Royal Shield",
        "Saracen's Chance",
        "Sharktooth Armor",
        "Spider Bow",
        "Swordguard",
        "Thundergod's Vigor",
        "Totemic Mask",
        "Chu-Ko-Nu",
        "Executioner Sword",
        "Giant Conch",
        "Godstrike Arch",
        "Heirophant Trophy",
        "Hyperion Javelin",
        "Scissors Quhab",
        "Slayer Guard",
        "Todesfaelle Flamme",
        "Tomahawk",
        "War Belt",
        "War Boots",
        "War Gauntlets",
        "Baezil's Vortex",
        "Cloudcrack",
        "Dwarf Star",
        "Guardian Angel",
        "Martel de Fer",
        "Matriarchal Bow",
        "Pompe's Wrath",
        "Raven Frost",
        "The Gavel of Pain",
        "The Minataur",
        "Coronet",
        "Deathbit",
        "Gothic Bow",
        "Grim's Burning Dead",
        "Husoldal Evo",
        "Kerke's Sanctuary",
        "Templar Coat",
        "The Vile Husk",
        "Truncheon",
        "Valkyrie Wing",
        "Ancient Axe",
        "Bec-de-Corbin",
        "Bing Sz Wang",
        "Ceremonial Pike",
        "Earthshaker",
        "Guilded Shield",
        "Harpoon",
        "Islestrike",
        "Magewrath",
        "Pierre Tombale Couant",
        "Winged Helm",
        "Arreat's Face",
        "Athena's Wrath",
        "Bartuc's Cutthroat",
        "Blackleach Blade",
        "Boneslayer Blade",
        "Bul-Kathos' Sacred Charge",
        "Bul-Kathos' Tribal Guardian",
        "Crainte Vomir",
        "Greater Talons",
        "Grim Helm",
        "Hand of Blessed Light",
        "Herald of Zakarum",
        "Homunculus",
        "Jalal's Mane",
        "Lavagout",
        "Lycander's Aim",
        "Lycander's Flank",
        "Moonfall",
        "Pavise",
        "Sacred Feathers",
        "Skullder's Ire",
        "Swirling Crystal",
        "The Atlantian",
        "The Oculus",
        "Titan's Revenge",
        "Wartraveler",
        "Ancient Sword",
        "Battle Belt",
        "Battle Boots",
        "Battle Gauntlets",
        "Blackhand Key",
        "Blackhorn's Face",
        "Cantor Trophy",
        "Cliffkiller",
        "Duriel's Shell",
        "Grave Wand",
        "Lidless Wall",
        "Plague Bearer",
        "Rune Bow",
        "Russet Armor",
        "Savage Helmet",
        "Skullcollector",
        "Snowclash",
        "Stormrider",
        "Stormspike",
        "The Meat Scraper",
        "Vampiregaze",
        "Zweihander",
        "Battle Hammer",
        "Death Mask",
        "Gothic Sword",
        "Grim Shield",
        "Naga",
        "Balista",
        "Butcher's Pupil",
        "Ceremonial Bow",
        "Cuirass",
        "Headstriker",
        "Lance",
        "Rune Staff",
        "Spellsteel",
        "Spire of Honor",
        "Sureshrill Frost",
        "Warpspear",
        "Whichwild String",
        "Blackbog's Sharp",
        "Darksight Helm",
        "Fleshrender",
        "Gothic Axe",
        "Hunter's Guise",
        "Long Siege Bow",
        "Protector Shield",
        "Shaftstop",
        "Sparkling Ball",
        "Spiculum",
        "Stilleto",
        "The Fetid Sprinkler",
        "Tiamat's Rebuke",
        "Basinet",
        "Crow Caw",
        "Divine Scepter",
        "Dragon Shield",
        "Ginther's Rift",
        "Gloomstrap",
        "Greater Claws",
        "Hone Sundan",
        "Mesh Armor",
        "Sexton Trophy",
        "Tusk Sword",
        "War Club",
        "Zakarum's Hand",
        "Arm of King Leoric",
        "Coldkill",
        "Endlesshail",
        "Ghoulhide",
        "Griswold's Heart",
        "Griswold's Honor",
        "Griswold's Valor",
        "Griswolds's Redemption",
        "Heart Carver",
        "Pus Spiter",
        "Rage Mask",
        "Rune Sword",
        "Silkweave",
        "Yari",
        "Blade of Ali Baba",
        "Carin Shard",
        "Ceremonial Spear",
        "Chromatic Ire",
        "Crowbill",
        "Cutlass",
        "Heavy Bracers",
        "Knout",
        "Lance Guard",
        "Mesh Belt",
        "Mesh Boots",
        "Naj's Circlet",
        "Naj's Light Plate",
        "Naj's Puzzler",
        "Short Siege Bow",
        "Soulfeast Tine",
        "Spiritforge",
        "Stealskull",
        "Stormchaser",
        "Tigulated Mail",
        "Tomb Wand",
        "Warlord's Trust",
        "Barbed Shield",
        "Casque",
        "Cinquedeas",
        "Dacian Falx",
        "Dark Clan Crusher",
        "Gothic Staff",
        "Linked Mail",
        "Scutum",
        "Tabar",
        "Cloudy Sphere",
        "Guillaume's Face",
        "Hand Scythe",
        "Hexfire",
        "Hurlbat",
        "Ironpelt",
        "Kelpie Snare",
        "Kuko Shakaku",
        "Magnus' Skin",
        "Suicide Branch",
        "War Fork",
        "Wihtstan's Guard",
        "Wilhelm's Pride",
        "Akaran Rondache",
        "Ancient Armor",
        "Battle Scythe",
        "Battle Sword",
        "Griffon Headress",
        "Holy Water Sprinkler",
        "Langer Briser",
        "Siege Crossbow",
        "Simbilan",
        "Spineripper",
        "Trellised Armor",
        "Waterwalk",
        "Ashwood Bow",
        "Bladebuckle",
        "Coldsteel Eye",
        "Credendum",
        "Culwens Point",
        "Double Bow",
        "Fetish Trophy",
        "Frostburn",
        "Gravepalm",
        "Heavenly Garb",
        "Jagged Star",
        "Laying of Hands",
        "Mosers Blessed Circle",
        "Rattlecage",
        "Razortail",
        "Ribcracker",
        "Riphook",
        "Rite of Passage",
        "Rockstopper",
        "Sharkskin Belt",
        "Sharkskin Boots",
        "Sharkskin Gloves",
        "Skin of the Flayerd One",
        "Spiritual Custodian",
        "Steeldriver",
        "Tearhaunch",
        "Telling of Beads",
        "The Grim Reaper",
        "The Humongous",
        "The Impaler",
        "The Patriarch",
        "The Stone of Jordan",
        "Twin Axe",
        "Undead Crown",
        "War Dart",
        "Bearded Axe ",
        "Blastbark",
        "Bloodletter",
        "Cedar Staff",
        "Doomspittle",
        "Goldskin",
        "Lion Helm",
        "Petrified Wand",
        "Rockfleece",
        "The Iron Jang Bong",
        "Umes Lament",
        "Victors Silk",
        "Woestave",
        "Bill",
        "Crystalline Globe",
        "Demonhide Armor",
        "Dimensional Blade",
        "Espadon",
        "Full Plate Mail",
        "Great Pilum",
        "Immortal King's Detail",
        "Immortal King's Forge",
        "Immortal King's Pillar",
        "Immortal King's Soul Cage ",
        "Immortal King's Stone Crusher",
        "Immortal King's Will",
        "Infernostride",
        "Round Shield",
        "Sallet",
        "Skin of the Vipermagi",
        "String of Ears",
        "Tulwar",
        "Venom Grip",
        "Demonhide Boots",
        "Demonhide Sash",
        "Fascia",
        "Fuscina",
        "Goldwrap",
        "Hellcast",
        "Hellclap",
        "Ironstone",
        "Peasent Crown",
        "Rakescar",
        "Razorswitch",
        "Rondel",
        "Serpentskin Armor",
        "Skystrike",
        "The Spirit Shroud",
        "The Tannr Gorerod",
        "Visceratuant",
        "Akaran Targe",
        "Alpha Helm",
        "Blacktongue",
        "Boneflesh",
        "Cedar Bow",
        "Ceremonial Javelin",
        "Flanged Mace",
        "Light Plate",
        "Partizan",
        "Quarterstaff",
        "Ripsaw",
        "Shamshir",
        "The Ward",
        "Wizendraw",
        "Arbalest",
        "Brainhew",
        "Cleaver",
        "Defender",
        "Francisca",
        "Ghost Armor",
        "Howltusk",
        "Irices Shard",
        "Military Axe",
        "Pullspite",
        "Sazabi's Cobalt Redeemer",
        "Sazabi's Ghost Liberator",
        "Sazabi's Mental Sheath",
        "The Battlebranch",
        "The Mahim-Oak Curio",
        "War Hat",
        "War Scythe",
        "Demonhide Gloves",
        "Great Sword",
        "Jawbone Visor",
        "Lochaber Axe",
        "Mummified Trophy",
        "Razor Bow",
        "Repeating Crossbow",
        "War Spear",
        "Barbed Club",
        "Bonesob",
        "Glowing Orb",
        "Gothic Plate",
        "Great Maul",
        "Rancid Gas Potion",
        "Trang-Oul's Claws",
        "Trang-Oul's Girth",
        "Trang-Oul's Guise",
        "Trang-Oul's Scales",
        "Trang-Oul's Wing",
        "Wrist Spike",
        "Battle Dart",
        "Burnt Wand",
        "Hatchet",
        "Kinemils Awl",
        "Long War Bow",
        "Magefist",
        "Poignard",
        "Rune Scepter",
        "Stormeye",
        "Cudgel",
        "Edge Bow",
        "Gladius",
        "Goblin Toe",
        "Gothic Shield",
        "Hellplague",
        "Iceblink",
        "Jo Staff",
        "Lance of Yaggai",
        "War Javelin",
        "Aldur's Advance",
        "Aldur's Deception",
        "Aldur's Gauntlet",
        "Aldur's Stony Gaze",
        "Crown",
        "Halberd",
        "Throwing Spear",
        "Field Plate",
        "Hwanin's Justice",
        "Hwanin's Refuge",
        "Hwanin's Seal",
        "Hwanin's Splendor",
        "Mindrend",
        "Oil Potion",
        "Quhab",
        "The Generals Tan Do Li Ga",
        "The Salamander",
        "Wormskull",
        "Flamberge",
        "Gauntlets",
        "Giant Axe",
        "Gravenspine",
        "Greaves",
        "Maiden Pike",
        "Nightsmoke",
        "Piercerib",
        "Plated Belt",
        "Reflex Bow",
        "Short War Bow",
        "Tancred's Crowbill",
        "Tancred's Hobnails",
        "Tancred's Skull",
        "Tancred's Spine",
        "Tancred's Weird",
        "The Face of Horror",
        "Venomsward",
        "Wall of the Eyeless",
        "War Sword",
        "Bverrit Keep",
        "Grim Wand",
        "Soul Harvest",
        "Soulflay",
        "Tal Rasha's Adjudication",
        "Tal Rasha's Fire-Spun Cloth",
        "Tal Rasha's Horadric Crest",
        "Tal Rasha's Howling Wind",
        "Tal Rasha's Lidless Eye",
        "The Chieftan",
        "The Jade Tan Do",
        "War Axe",
        "War Hammer",
        "Avenger Guard",
        "Bastard Sword",
        "Circlet",
        "Crown Shield",
        "Demon Head",
        "Dragon Stone",
        "Heavy Crossbow",
        "Ichorsting",
        "Lazarus Spire",
        "Pike",
        "Plate Mail",
        "Scissors Katar",
        "Spirit Mask",
        "War Staff",
        "Blade",
        "Bloodthief",
        "Duskdeep",
        "Glaive",
        "Great Axe",
        "Great Helm",
        "Griswolds Edge",
        "Long Battle Bow",
        "Maiden Javelin",
        "Milabrega's Diadem",
        "Milabrega's Orb",
        "Milabrega's Robe",
        "Milabrega's Rod",
        "Rusthandle",
        "Sparking Mail",
        "Steelclash",
        "Bone Helm",
        "Natalya's Mark",
        "Natalya's Shadow",
        "Natalya's Soul",
        "Natalya's Totem",
        "Tower Shield",
        "Twitchthroe",
        "Blade Talons",
        "Giant Sword",
        "Iratha's Coil",
        "Iratha's Collar",
        "Iratha's Cord",
        "Iratha's Cuff",
        "M'avina's Caster",
        "M'avina's Embrace",
        "M'avina's Icy Clutch",
        "M'avina's Tenet",
        "M'avina's True Sight",
        "Maul",
        "PoleAxe",
        "War Scepter",
        "Aerin Shield",
        "Arcanna's Deathwand",
        "Arcanna's Flesh",
        "Arcanna's Head",
        "Arcanna's Sign",
        "Assault Helmet",
        "Bladebone",
        "Bloodrise",
        "Chance Guards",
        "Choking Gas Potion",
        "Cow King's Hide",
        "Cow King's Hoofs",
        "Cow King's Horns",
        "Falcon Mask",
        "Gargoyle Head",
        "Hawkmail",
        "Heavy Belt",
        "Light Gauntlets",
        "Light Plated Boots",
        "Long Sword ",
        "Manald Heal",
        "Rimeraven",
        "Sander's Paragon",
        "Sander's Riprap",
        "Sander's Superstition",
        "Sander's Taboo",
        "Spetum",
        "Splint Mail",
        "Swordback Hold",
        "Tarnhelm",
        "The Eye of Etlich",
        "Treads of Cthon",
        "Bone Shield",
        "Coif of Glory",
        "Darkglow",
        "Flail",
        "Goreshovel",
        "Maelstrom",
        "Mask",
        "Military Pick",
        "Steelgoad",
        "The Centurion",
        "Vidala's Ambush",
        "Vidala's Barb",
        "Vidala's Fetlock",
        "Vidala's Snare",
        "Bone Wand",
        "Breast Plate",
        "Claws",
        "Gleamscythe",
        "Maiden Spear",
        "Short Battle Bow",
        "Stag Bow",
        "Stormguild",
        "Witherstring",
        "Angelic Halo",
        "Angelic Mantle",
        "Angelic Sickle",
        "Angelic Wings",
        "Battle Axe",
        "Battle Staff",
        "Clasped Orb",
        "Claymore",
        "Kris",
        "Antlers",
        "Balanced Axe",
        "Blinkbats Form",
        "Brandistock",
        "Exploding Potion",
        "Heraldic Shield",
        "Horned Helm",
        "Razortine",
        "Shadowfang",
        "Snakecord",
        "Unraveller Head",
        "Broad Sword",
        "Cathan's Mesh",
        "Cathan's Rule",
        "Cathan's Seal",
        "Cathan's Sigil",
        "Cathan's Visage",
        "Cestus",
        "Chain Mail",
        "Crossbow",
        "Full Helm",
        "Grand Scepter",
        "Kite Shield",
        "Scythe",
        "Short Spear",
        "The Diggler",
        "Krintizs Skewer",
        "Nokozan Relic",
        "Balanced Knife",
        "Civerb's Cudgel",
        "Civerb's Icon",
        "Civerb's Ward",
        "Double Axe",
        "Morning Star",
        "Scale Mail",
        "Belt",
        "Bloodfist",
        "Broad Axe ",
        "Chain Boots",
        "Chain Gloves",
        "Composite Bow",
        "Crushflange",
        "Deathspade",
        "Gnarled Staff",
        "Gorefoot",
        "Hatchet Hands",
        "Leadcrow",
        "Serpent Lord",
        "Smoked Sphere",
        "Umbral Disk",
        "Yew Wand",
        "Crystal Sword",
        "Dimoaks Hew",
        "Falchion",
        "Fechmars Axe",
        "Helm",
        "Isenhart's Case",
        "Isenhart's Horns",
        "Isenhart's Lightbrand",
        "Isenhart's Parry",
        "Large Shield",
        "Ring Mail",
        "Spiked Shield",
        "The Dragon Chang",
        "Voulge",
        "Blood Crescent",
        "Greyform",
        "Lenymo",
        "Nagelring",
        "Pilum",
        "Pluckeye",
        "Two-Handed Sword",
        "Dirk",
        "Sigon's Gage",
        "Sigon's Guard",
        "Sigon's Sabot",
        "Sigon's Shelter",
        "Sigon's Visor",
        "Sigon's Wrap",
        "Trident",
        "Wrist Blade",
        "Death's Guard",
        "Death's Hand",
        "Death's Touch",
        "Fanged Helm",
        "Hawk Helm",
        "Long Bow",
        "Long Staff",
        "Mace",
        "Rondache",
        "Sabre",
        "Sacred Globe",
        "Strangling Gas Potion",
        "Studded Leather ",
        "Zombie Head",
        "Bane Ash",
        "Heavy Boots",
        "Heavy Gloves",
        "Hotspur",
        "Infernal Cranium",
        "Infernal Sign",
        "Infernal Torch",
        "Iros Torch",
        "Knell Striker",
        "Light Belt",
        "Axe",
        "Stoutnail",
        "The Gnasher",
        "The Hand of Broc",
        "Throwing Axe",
        "Cleglaw's Claw",
        "Cleglaw's Pincers",
        "Cleglaw's Tooth",
        "Gull",
        "Large Axe",
        "Light Crossbow",
        "Bardiche",
        "Berserker's Hatchet",
        "Berserker's Hauberk",
        "Berserker's Headgear",
        "Hard Leather Armor",
        "Hunter's Bow",
        "Scimitar",
        "Skull Cap",
        "Small Shield",
        "Spear",
        "Felloak",
        "Fulminating Potion",
        "Hsarus' Iron Fist",
        "Hsarus' Iron Heel",
        "Hsarus' Iron Stay",
        "Jawbone Cap",
        "Preserved Head",
        "Spiked Club",
        "Targe",
        "War Bonnet",
        "Wolf Head",
        "Arctic Binding",
        "Arctic Furs",
        "Arctic Horn",
        "Arctic Mitts",
        "Dagger",
        "Hand Axe",
        "Leather Armor",
        "Leather Boots",
        "Leather Gloves",
        "Pelta Lunata",
        "Rixots Keen",
        "Sash",
        "Scepter",
        "Throwing Knife",
        "Wand",
        "Buckler",
        "Cap",
        "Club",
        "Eagle Orb",
        "Javelin",
        "Katar",
        "Quilted Armor",
        "Short Bow",
        "Short Staff",
        "Short Sword",
        "Amulet of the Viper",
        "Gidbinn",
        "Horadric Malus",
        "Horadric Staff",
        "Wirt's Leg"
    ]
    
    var limit = 6;
    $('#search').keyup(function() {
        var query = this.value;
        var hints = new Array();
        
        if (this.value == '') {
            $('.js-autocomplete').remove(); return false;
        }
        
        for (var i in itemNames) {
            if (itemNames[i].toLowerCase().slice(0, query.length) == query.toLowerCase()) {
                hints.push(itemNames[i]);
            }
            if (hints.length >= limit) { 
                break; 
            }
        }
        
        $('.js-autocomplete').remove();
        for (var i in hints) {
            var urlname = hints[i].replace(/[ ]/g, "-").replace(/'/g, '').toLowerCase();
            $('#autocomplete').append("<li class='js-autocomplete'><a class='link-autocomplete' href='/loot?item=" + urlname + "'>" + hints[i].slice(0, this.value.length) + "<b>" + hints[i].slice(this.value.length, hints[i].length) + "</b>" + "</a></li>");
        }
    });
});